
[general]
import = [
	"~/.config/alacritty/themes/ayu-dark.toml",
]

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 1.0
#opacity = 1
blur = true

[font]
size = 11

[font.normal]
family = "Liberation Mono"

