general {

	hide_cursor = true
	grace = 5
	ignore_empty_input = true
}


auth {

	pam:enabled = true

}


animations {

	enabled = true 

}


background {
	
	monitor = 
	#path = /home/lars/Nextcloud/Pictures/Wallpapers/foggy-hills.jpg
	path = ~/.config/img/wallpaper.png

}

image {
	# Replace with your face icon
	path = /usr/share/sddm/faces/lars.face.icon
	border-size = 0
	size = 160
	rounding = -1
	position = 0, 180
}


label {
	monitor = DP-1
	text = cmd[update:1000] echo "$(date +'%R')"
	color = rgba (255, 255, 255, 1.0)
	font_size = 48
	font_family = "Liberation Mono"
	position = 0, 20
}

label {
	monitor = DP-1
	text = cmd[update:0] echo "Welcome back $(whoami)"
	color = rgba(255, 255, 255, 1.0)
	font_size = 24
	font_family = "Liberation Mono"
	position = 0, -40
}

input-field {
	monitor = DP-1
	inner_color = rgba(61, 72, 77, 1)
	font_color = rgba(211, 198, 170, 1)

	outer_color = rgb(859289) rgb(9da9a0) 45deg
	check_color = rgb(d3c6aa) rgb(dbbc7f) 45deg
	fail_color = rgb(e69875) rgb(e67e80) 40def

	position = 0, -180
	halign = center
	valign = center
	
	fade_on_empty = false
	placeholder_text = Enter password
	capslock_text = "CAPSLOCK"

}


